### ISSUE TITLE
TODO: Dock

### ISSUE THREAD

**Issue by mszoek** [ravynsoft/ravynos#163]
We need one.

**Comment by gonzoMD** [comment]
Latte Dock?
It's based on plasma. Are there any reasons not to port it?

**Comment by mszoek** [comment]
> Latte Dock? It's based on plasma. Are there any reasons not to port it?

Yep, Latte Dock!

**Comment by dakk** [comment]
@mszoek I also think a simple new one dock from scratch is a better idea, but anyway I link you also these docks:
- https://github.com/rodolf0/wbar (no qt/gtk deps, only x11 and imlib)
- https://gitlab.com/o9000/tint2 (cairo/gdk) 

Maybe wbar could be a better starting point, since has less code and less deps

**Comment by mszoek** [comment]
The story so far.

![image](https://user-images.githubusercontent.com/60144291/149242452-88ee273e-b87b-412d-97d4-0560f42f81b2.png)

**Comment by mszoek** [comment]
A rudimentary dock was added with https://github.com/ravynsoft/ravynos/pull/295, although lots still needs to be done on it.
