### ISSUE TITLE
dahliaOS's flutter based UI layer could be a perfect fit

### ISSUE THREAD

**Issue by lin72h** [ravynsoft/ravynos#234]
I just found out a really cool project called [dahliaOS](https://docs.dahliaos.io/) which use macOS alike flutter based UI with swappable Fuchsia and Linux Kernel.

There's a crazy [web version](https://web.dahliaos.io/#/) for preview(I think it's a feature of Flutter which has a web backend)

Seems to be a perfect fit for airyx's UI layer
<img width="1169" alt="Screen Shot 2022-03-07 at 16 32 45" src="https://user-images.githubusercontent.com/93238608/156995720-97b47f8b-0b42-4eaf-86c2-1076a9895669.png">

There's a [video](https://www.youtube.com/watch?v=gqER_NKG2fQ) review

**Comment by Gambulec** [comment]
It doesn't look like a mac os. It looks more like Windows or a gnome. This interface would not even integrate with mac os applications.

**Comment by linz2h** [comment]
> It doesn't look like a mac os. It looks more like Windows or a gnome. This interface would not even integrate with mac os applications.

The visual thing like button position can be easily changed, what I'm excited about is the Skia based rendering architecture, it BSD licensed, cover everything we need like layout, text and it's fast because of the native Metal and Vulkan based backed.

I believe it's better than QT or GNOME based solution

**Comment by Gambulec** [comment]
The only thing that this interface has in common with mac os is the blur effect, something that could be done now at a low cost. Qt is a solid technology that is used by mac os itself. To abandon this in favor of an experimental technology that doesn't even work anywhere yet is very unwise, especially since the advantage of airyx is to be compatibility. Projects like, dahliaos have been appearing cyclically in recent years, Reddit has fallen into delight at the sight of a few screenshots, and after a few months there are no signs of life.

**Comment by ashifolfi** [comment]
We are making our own ui but thanks for the suggestion!

**Comment by mszoek** [comment]
Won't fix
