### ISSUE TITLE
v0.4.0pre4 - Ravyn menu bug (or feature?)

### ISSUE THREAD

**Issue by markshank** [ravynsoft/ravynos#294]
Click on the Ravyn icon in the menu bar and the drop down menu is displayed.  Then click on the desktop and a popup menu appears near the mouse pointer.

But the Ravyn menu does not disappear, it is still active.  Must click on the Ravyn icon again to make the menu go away.

That is different behavior from Big Sur on my MacBook Air.

**Comment by mszoek** [comment]
Good catch! This is an artifact of not having Cocoa manging the actual desktop yet - Dock.app will do that soon, and a click should then go to it instead of the compositor directly. You can click anywhere on the menu bar to cancel menus as well.

That compositor pop-up menu will go away soon, now that things are a little more stable :)

**Comment by mszoek** [comment]
This is fixed for 0.5.2.
