### ISSUE TITLE
[Request] Ravynos

### ISSUE THREAD

**Issue by jhay06** [ravynsoft/ravynos#300]
Hi ,

I love the project and idea, it looks like it's the same idea as darling on linux

i would like to help with this project , but before that can i ask ? what tools or IDE did you use and how can i debug this without installing  ? 

Thanks

**Comment by mszoek** [comment]
Hi!

Yes, very similar to Darling in several ways. I like to think of ravynOS as akin to ReactOS but for Mac.

Help is totally welcome! At this stage, ravynOS is self-hosting... you need to use it to build it. Xcode on Mac can be used to build applications that build on ravynOS with a little porting work (Makefiles vs pbxproj, compiling & copying binary NIB files). They can also be written by hand without NIBs if you know how Cocoa works. Most of what I've done has been in tmux + vim on the running system (where I am right now!).

If you are working on low-level or CLI stuff, a VM will work. It has everything except a GUI because we don't yet have video drivers for virtual GPUs. To work on apps or UI, you probably do need to install it on some real hardware: Intel HD/Iris series, AMD embedded, and Radeon GPUs are currently supported.
