### ISSUE TITLE
When will ravynOS have VMware and virtualbox GPU drivers?

### ISSUE THREAD

**Issue by dsk502** [ravynsoft/ravynos#388]
I downloaded ravynOS_0.4.0pre4_f14_amd64.iso and tried it in VMware Fusion and VirtualBox, but it didn't show the desktop environment. When will ravynOS iso have the virtual machine GPU drivers? I know there is a repository named drm-kmod, which is the GPU drivers. What's the progress of its development? Is the drivers able to run now?

**Comment by Anvith00** [comment]
Work on VM graphics have been held and instead the leads devs have choosen to move forward with developing the OS on bare metal for the time being. Enough time has been expended trying to making acceleration work on ravynOS on both Wayland and X11 solutions, but in vain due to a lack of drivers or some other issue(s). 
VM graphics acceleration is not at the highest priority at this moment of time and thus won't be coming soon. Most of the testing would have be done using liveCD or installation (recommended to install on a separate device to avoid wiping your data by accident), or perhaps using GPU passthrough on QEMU (GPU passthrough is a hit or miss).

**Comment by mszoek** [comment]
Someone is still working on vmwgfx part time. We use drm-kmod for the intel and AMD drivers. It doesn't have any support for VMs. As noted above, I'll continue hacking on the desktop using a real machine for now.

**Comment by lexyclear** [comment]
> I downloaded ravynOS_0.4.0pre4_f14_amd64.iso and tried it in VMware Fusion and VirtualBox, but it didn't show the desktop environment. When will ravynOS iso have the virtual machine GPU drivers? I know there is a repository named drm-kmod, which is the GPU drivers. What's the progress of its development? Is the drivers able to run now?

currently your best bet is to just install regular mac os on a vm. as they here do not want to make it run on a vm at all apparently.
also if you are doing bare metal be ready to see it fail often or not work at all if you are using amd.

**Comment by Anvith00** [comment]
> as they here do not want to make it run on a vm at all apparently.

A volunteer working on vmwgfx for FreeBSD did manage to obtain certain progress a few months ago with rendering Wayland albeit with still a few kernel panics and bugs to squash. Unfortunately, they've been also quite busy with life stuff (Most of the volunteers for this project are day-shift working employees in the tech industry).
