### ISSUE TITLE
Server edition

### ISSUE THREAD

**Issue by mcandre** [ravynsoft/ravynos#75]
Wow, what an exciting project! I'd love to see a headless edition, for use as remote SSH servers, build bots, etc.

**Comment by imrohitkumar** [comment]
Seems nice idea to me. Airyx should release two versions one for desktop and another for server.

**Comment by OpenOS-Project-Creator-Founder** [comment]
They can make 2 releases & ship 3 images -- [ISO / Disk.img.xz].

1 for Desktop GUI -- [ISO / Disk.img.xz]

1 for Server CLI/GUI -- [ISO / Disk.img.xz]

1 that has both. [ What I mean is since it's FreeBSD use Jails. Using AiryxOS Formally & Chrrently RavynOS as the host with the CLI Server release as a Jail & using its snapshotting/subvoluming features to import/export changes to bootable images for shipment & to the host system to then boot into the new snapshot/subvolume on the next boot/reboot. By doing this it allows faster development & simplicity] -- [ISO / Disk.img.xz]

**Comment by arclight2020** [comment]
I think this would be a good option

**Comment by linz2h** [comment]
Even without the Graphic, FreeBSD with Mach IPC already a huge win.
